seaf.ba.products:

#  flix.media_platform_self:
#    title: Медиа-платформа
#    used_in:
#      - flix.home_cinema
#    owner: flix.team.product

  flix.home_cinema:
    title: Домашний кинотеатр
    sber:
      status: Используется
    owner: flix


  flix.consume_content:
    title: Предоставление (просмотр) медиа-контента по запросу
    owner: flix.team.product
    used_in:
      - flix.home_cinema
      - flix.mobile_app
      - flix.web_app
    sber:
      status: Используется

  alfa.payments:
    title: Прием платежей
    used_in:
      - flix.home_cinema
      - flix.web_app
    owner: alfa

  alfa.fl_auth:
    title: Аутентификация пользователей
    owner: alfa
    used_in:
      - flix.home_cinema
      - flix.web_app
      - flix.mobile_app

  flix.media_platform_saas:
    title: Медиа-платформа (SaaS)
    owner: flix
    sber:
      status: Используется


  flix.media_platform:
    title: Медиа-платформа
    owner: flix.team.product
    used_in:
      - flix.media_platform_saas
      - flix.consume_content

  flix.mobile_app:
    title: Мобильное приложение для пользователей
    owner: flix
    sber:
      status: Используется
      type: Канал
      channel_type: Цифровой

  flix.web_app:
    title: Веб-приложение для пользователей
    owner: flix
    sber:
      status: Используется
      type: Канал
      channel_type: Цифровой

  flix.partner_catalog:
    title: Каталог контента для партнера
    sber:
      status: Используется
    owner: flix

  flix.content_catalog:
    title: Каталог контента
    owner: flix.team.product
    used_in:
      - flix.partner_catalog
      - flix.media_platform

  flix.content_search:
    title: Поиск медиа-контента
    owner: flix.team.product
    used_in:
      - flix.media_platform

  flix.support:
    title: Оказание поддержки клиентам
    owner: flix.team.support
    used_in:
      - flix.media_platform_saas

  flix.support_channels:
    title: Каналы взаимодействия с клиентом по оказанию поддержки
    owner: flix.team.support
    sber:
      type: Канал
      channel_type: Цифровой
    used_in:
      - flix.support

  flix.support_channels.telegram:
    title: Поддержка пользователей в телеграм
    owner: flix.team.support
    used_in:
      - flix.support_channels
    sber:
      type: Канал
      channel_type: Цифровой

  flix.support_channels.email:
    title: Поддержка пользоваталей через почту
    owner: flix.team.support
    used_in:
      - flix.support_channels
    sber:
      type: Канал
      channel_type: Цифровой
