seaf.ba.products:

#  sber.berezka.media_platform_self:
#    title: Медиа-платформа
#    used_in:
#      - sber.berezka.home_cinema
#    owner: sber.berezka.team.product

  sber.berezka.home_cinema:
    title: Домашний кинотеатр
    owner: sber.berezka
    sber:
      status: Используется

  sber.berezka.consume_content:
    title: Предоставление (просмотр) медиа-контента по запросу
    owner: sber.berezka.team.product
    used_in:
      - sber.berezka.home_cinema
      - sber.berezka.mobile_app
      - sber.berezka.web_app
    sber:
      status: Используется

  sber.center.payments:
    title: Прием платежей
    used_in:
      - sber.berezka.home_cinema
      - sber.berezka.web_app
    owner: sber.center

  sber.center.fl_auth:
    title: Аутентификация пользователей
    owner: sber.center
    used_in:
      - sber.berezka.home_cinema
      - sber.berezka.web_app
      - sber.berezka.mobile_app

  sber.berezka.media_platform_saas:
    title: Медиа-платформа (SaaS)
    owner: sber.berezka
    sber:
      status: Используется

  sber.berezka.media_platform:
    title: Медиа-платформа
    owner: sber.berezka.team.product
    used_in:
      - sber.berezka.media_platform_saas
      - sber.berezka.consume_content

  sber.berezka.mobile_app:
    title: Мобильное приложение для пользователей
    owner: sber.berezka
    sber:
      status: Используется
      subtype: Канал
      type: Цифровой

  sber.berezka.web_app:
    title: Веб-приложение для пользователей
    owner: sber.berezka
    sber:
      status: Используется
      subtype: Канал
      type: Цифровой

  sber.berezka.partner_catalog:
    title: Каталог контента для партнера
    owner: sber.berezka
    sber:
      status: Используется

  sber.berezka.content_catalog:
    title: Каталог контента
    owner: sber.berezka.team.product
    used_in:
      - sber.berezka.partner_catalog
      - sber.berezka.media_platform

  sber.berezka.content_search:
    title: Поиск медиа-контента
    owner: sber.berezka.team.product
    used_in:
      - sber.berezka.media_platform

  sber.berezka.support:
    title: Оказание поддержки клиентам
    owner: sber.berezka.team.support
    used_in:
      - sber.berezka.media_platform_saas

  sber.berezka.support_channels:
    title: Каналы взаимодействия с клиентом по оказанию поддержки
    owner: sber.berezka.team.support
    sber:
      subtype: Канал
      type: Цифровой
    used_in:
      - sber.berezka.support

  sber.berezka.support_channels.telegram:
    title: Поддержка пользователей в телеграм
    owner: sber.berezka.team.support
    used_in:
      - sber.berezka.support_channels
    sber:
      subtype: Канал
      type: Цифровой

  sber.berezka.support_channels.email:
    title: Поддержка пользоваталей через почту
    owner: sber.berezka.team.support
    used_in:
      - sber.berezka.support_channels
    sber:
      subtype: Канал
      type: Цифровой
