seaf.ba.products:

#  flix.media_platform_self:
#    title: Медиа-платформа
#    used_in:
#      - flix.home_cinema
#    owner: flix.team.product

  flix.home_cinema:
    title: Домашний кинотеатр
    owner: flix
    exposed:
      group.entertainment.cinema:
        title: Домашний кинотеатр для группы

    sber:
      status: Используется

  flix.consume_content:
    title: Предоставление (просмотр) медиа-контента по запросу
    owner: flix.team.product
    used_in:
      - flix.home_cinema
      - flix.mobile_app
      - flix.web_app
    sber:
      status: Используется

  alfa.payments:
    title: Прием платежей
    used_in:
      - flix.home_cinema
      - flix.web_app
    owner: alfa
    exposed:
      group.enablers.payments:
        title: Единая система приема платежей

  alfa.fl_auth:
    title: Аутентификация пользователей
    owner: alfa
    used_in:
      - flix.home_cinema
      - flix.web_app
      - flix.mobile_app
    exposed:
      group.enablers.id:
        title: alfaID

  flix.media_platform_saas:
    title: Медиа-платформа (SaaS)
    owner: flix
    exposed:
      group.b2b.payments:
        title: Медиа-платформа (SaaS)

    sber:
      status: Используется

  flix.media_platform:
    title: Медиа-платформа
    owner: flix.team.product
    used_in:
      - flix.media_platform_saas
      - flix.consume_content

  flix.mobile_app:
    title: Мобильное приложение для пользователей
    owner: flix
    sber:
      status: Используется
      subtype: Канал
      type: Цифровой

  flix.web_app:
    title: Веб-приложение для пользователей
    owner: flix
    sber:
      status: Используется
      subtype: Канал
      type: Цифровой

  flix.partner_catalog:
    title: Каталог контента для партнера
    owner: flix
    sber:
      status: Используется

  flix.content_catalog:
    title: Каталог контента
    owner: flix.team.product
    used_in:
      - flix.partner_catalog
      - flix.media_platform

  flix.content_search:
    title: Поиск медиа-контента
    owner: flix.team.product
    used_in:
      - flix.media_platform

  flix.support:
    title: Оказание поддержки клиентам
    owner: flix.team.support
    used_in:
      - flix.media_platform_saas

  flix.support_channels:
    title: Каналы взаимодействия с клиентом по оказанию поддержки
    owner: flix.team.support
    sber:
      subtype: Канал
      type: Цифровой
    used_in:
      - flix.support

  flix.support_channels.telegram:
    title: Поддержка пользователей в телеграм
    owner: flix.team.support
    used_in:
      - flix.support_channels
    sber:
      subtype: Канал
      type: Цифровой

  flix.support_channels.email:
    title: Поддержка пользоваталей через почту
    owner: flix.team.support
    used_in:
      - flix.support_channels
    sber:
      subtype: Канал
      type: Цифровой
