#Пример создания требования на базе сущности Требование SEAF DZO CORE (с дополнительными Сбер-специфичными атрибутами)
seaf.change.requirements:
  alfa.standards.sbornik_dzo_db.p7.ТАСАР_2-P07.APP-1-03:
    title: Система должна быть реализована в компонентной архитектуре
    statement: >- #<------Здесь нужна ровно такая конструкция - знак больше и минус
      Система должна быть реализована в компонентной архитектуре, 
      а именно должна состоять из слабо связанных компонентов, 
      взаимодействующих друг с другом с помощью универсальных 
      (не зависящих от среды разработки и исполнения) интеграционных интерфейсов (API).
    type:
      - non-functional
    description: Дополнительное описание
    drivers:
      - Предотвращение рисков (согласно политике по управлению риском технологий Группы). Риск некорректных изменений АС/БС
      - Уменьшение затрат на доработку и поддержку АС
      - Уменьшение времени на разработку и тестирование АС
      - Уменьшение Time-to-Market
      - Повышение качества
    exceptions_acceptance_level: см. правило определения уровня согласования для отклонений
    stakeholders:
      - ДКА
    tags:
      - Архитектура приложений
    comments: Дополнительные комментарии для таблиц
    sber:
      id_sib: ТАСАР_2-P07.ПА-1-03
      id_sib_previous: ТАСАР_2-P07.ПА-1-03 #код предыдущей версии для требований у которых не изменился текст но изменился код
      standard_version: 3.1
      applicability_level:
        - Все
      obj_und_ctrl:
        - sber.obj.servers
        - sber.obj.monitoring
