components:
  sber.berezka.home_cinema:
    entity: frame
    description: Домашний кинотеатр
    title: Домашний кинотеатр

  sber.berezka.home_cinema.recomendation:
    entity: component
    title: Рекомендации
    type: service

  sber.berezka.home_cinema.catalog:
    entity: component
    title: Каталог фильмов
    description: Каталог фильмов
    type: service
    sber:
      criticality: Business Critical
      role_model: Централизованная
      class: Продуктовая фабрика (основная деятельность)

  sber.berezka.home_cinema.payments:
    entity: component
    title: Платежи
    description: Осуществление платежей пользователей за подписки
    aspects:
      - sber.berezka.home_cinema.payments
    type: service
    sber:
      criticality: Business Operational
      role_model: Централизованная
      class: Иное

  sber.berezka.home_cinema.canals:
    entity: component
    title: ТВ-Каналы
    description: Трансляция ТВ-каналов
    aspects:
      - sber.berezka.home_cinema.catalog.multiplex.c1
      - sber.berezka.home_cinema.catalog.multiplex.c2
    type: service
    sber:
      criticality: Business Operational
      role_model: Централизованная
      class: Иное

  sber.berezka.home_cinema.auth:
    entity: component
    title: Прикладной сервис аутентификации
    description: Авторизация пользователей для доступа к Домашнему кинотеарту
    type: service
    sber:
      criticality: Business Critical
      role_model: Централизованная
      class: Клиентский профиль (Customer Information File)

  sber.berezka.1c:
    entity: component
    title: 1C
    type: service
    sber:
      role_model: Нецентрализованная
      criticality: Office Productivity
      class: Бухгалтерия и финансы